### ISSUE TITLE
The command could not be executed

### ISSUE THREAD

**Issue by yuqian114514** [DarkSavci/Minecraft-Video-Player#4]
![image](https://github.com/user-attachments/assets/7bcbd624-aeb7-492f-8d2e-e663e8756e9d)
Here's the thing:
I executed /processimage https://zi9bdznvfiucgmuqmgh2m5lrdp9utz70lhqy5aa6k9l7sj7yy7.free-lbv3.idouyinvod.com/v83-017.douyinvod.com/b641a64c025a91c08dd1bcc1736fe7f3/6772a8e7/video/tos/cn/tos-cn-ve-15/o8EZEDbfjaSIFoA90iZn2RF2e0ZDmVgAAd27mB/?a=1128&ch=0&cr=0&dr=0&cd=0%7 in the game 
Then the game prompts: An internal error occurred while attempting to perform this command
The server background displays: 
[21:04:02 INFO]: RealmMiracle issued server command: /processimage https://zi9bdznvfiucgmuqmgh2m5lrdp9utz70lhqy5aa6k9l7sj7yy7.free-lbv3.idouyinvod.com/v83-017.douyinvod.com/b641a64c025a91c08dd1bcc1736fe7f3/6772a8e7/video/tos/cn/tos-cn-ve-15/o8EZEDbfjaSIFoA90iZn2RF2e0ZDmVgAAd27mB/?a=1128&ch=0&cr=0&dr=0&cd=0%7
[21:04:02 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'processimage' in plugin Minecraft-Video-Player v1.1 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[leaves-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[leaves-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:918) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[leaves-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2317) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2271) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:187) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1325) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1318) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1452) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:309) ~[leaves-1.19.2.jar:git-Leaves-"98129c8"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Thexiaoyuqaq** [comment]
大概是多线程端导致的
